[build]
  command = "npm run build"
  publish = "dist"
  base = "./"
  environment = { NODE_VERSION = "18" }

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
